/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Design tokens from Stitch UI
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434657',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#747688',
        'outline-variant': '#c4c5da',
        'surface-tint': '#0046fa',
        primary: '#0035c5',
        'on-primary': '#ffffff',
        'primary-container': '#0047ff',
        'on-primary-container': '#d4d9ff',
        'inverse-primary': '#b9c3ff',
        secondary: '#006c46',
        'on-secondary': '#ffffff',
        'secondary-container': '#50fcb1',
        'on-secondary-container': '#00714a',
        tertiary: '#3a495f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#516177',
        'on-tertiary-container': '#ccdcf7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b9c3ff',
        'on-primary-fixed': '#001257',
        'on-primary-fixed-variant': '#0033c0',
        'secondary-fixed': '#54feb3',
        'secondary-fixed-dim': '#27e199',
        'on-secondary-fixed': '#002112',
        'on-secondary-fixed-variant': '#005234',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        background: '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        'base': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'container-margin': '20px',
        'gutter': '16px',
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'numeric-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'sm': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)',
        'md': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
        'card': '0 2px 8px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
