import { useMemo } from 'react';
import { useApp } from '../contexts/AppContext';
import { formatAmount } from '../lib/stellar';
import { FileText, TrendingUp, AlertCircle } from 'lucide-react';
import BottomNav from '../components/ui/BottomNav';

export default function Insights() {
  const { transactions, user } = useApp();

  const stats = useMemo(() => {
    const sent = transactions.filter((tx) => tx.type === 'sent');
    const received = transactions.filter((tx) => tx.type === 'received');
    const totalSent = sent.reduce((sum, tx) => sum + tx.amountUSD, 0);
    const totalReceived = received.reduce((sum, tx) => sum + tx.amountUSD, 0);
    const netFlow = totalReceived - totalSent;

    const currentYear = new Date().getFullYear();
    const ytdTxs = transactions.filter((tx) => new Date(tx.timestamp).getFullYear() === currentYear);
    const ytdIncome = ytdTxs.filter((tx) => tx.type === 'received').reduce((sum, tx) => sum + tx.amountUSD, 0);

    return { totalSent, totalReceived, netFlow, ytdIncome, txCount: transactions.length };
  }, [transactions]);

  const handleGenerateProof = () => {
    const currentYear = new Date().getFullYear();
    const printContent =
      '<!DOCTYPE html><html><head><title>Proof of Income - StellarNest</title>' +
      '<style>body{font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:auto}' +
      'h1{font-size:24px;color:#131b2e}h2{font-size:18px;color:#0047ff;border-bottom:2px solid #0047ff;padding-bottom:8px}' +
      'table{width:100%;border-collapse:collapse;margin:20px 0}th{background:#0047ff;color:white;padding:10px;text-align:left}' +
      'td{padding:10px;border-bottom:1px solid #eee}.highlight{background:#f2f3ff;padding:16px;border-radius:8px;margin:16px 0}' +
      '.amount{font-size:28px;font-weight:bold;color:#006c46}</style></head><body>' +
      '<h1>StellarNest</h1><h2>Proof of Income Statement</h2>' +
      '<div class="highlight"><p><strong>Name:</strong> ' +
      (user?.name ?? 'N/A') +
      '</p><p><strong>Email:</strong> ' +
      (user?.email ?? 'N/A') +
      '</p><p><strong>Stellar Public Key:</strong> ' +
      (user?.stellarPublicKey ?? 'N/A') +
      '</p><p><strong>Statement Period:</strong> ' +
      currentYear +
      ' (Year-to-Date)</p></div>' +
      '<h2>Income Summary</h2><div class="highlight"><p>YTD Total Income Received</p>' +
      '<p class="amount">' +
      formatAmount(stats.ytdIncome) +
      '</p></div>' +
      '<table><tr><th>Date</th><th>Description</th><th>Amount</th><th>Status</th></tr>' +
      transactions
        .filter((tx) => tx.type === 'received')
        .map(
          (tx) =>
            '<tr><td>' +
            new Date(tx.timestamp).toLocaleDateString() +
            '</td><td>' +
            tx.counterpartyName +
            ' - ' +
            tx.description +
            '</td><td style="color:green">+' +
            formatAmount(tx.amountUSD) +
            '</td><td>' +
            tx.status +
            '</td></tr>'
        )
        .join('') +
      '</table><p style="margin-top:40px;font-size:12px;color:#666;text-align:center">' +
      'Generated by StellarNest on ' +
      new Date().toISOString() +
      '</p></body></html>';

    const win = window.open('', '_blank');
    if (win) {
      win.document.write(printContent);
      win.document.close();
      win.print();
    }
  };

  return (
    <div className="min-h-screen bg-background pb-28 max-w-lg mx-auto w-full">
      {/* Header */}
      <div className="px-5 pt-6 mb-6">
        <h2 className="font-semibold text-[24px] text-on-surface">Insights</h2>
      </div>

      <div className="px-5 space-y-5">
        {/* YTD Income */}
        <div className="bg-white rounded-2xl border border-surface-variant p-5">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp size={18} className="text-secondary" />
            <p className="text-[12px] font-bold uppercase tracking-wide text-on-surface-variant">
              Year-to-Date Income
            </p>
          </div>
          <p className="text-[32px] font-bold text-secondary leading-none mb-1">
            {formatAmount(stats.ytdIncome)}
          </p>
          <p className="text-[12px] text-on-surface-variant mt-1">
            Across {transactions.filter((t) => t.type === 'received').length} received transactions
          </p>
        </div>

        {/* Summary Grid */}
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-white rounded-2xl border border-surface-variant p-4">
            <p className="text-[11px] font-semibold uppercase text-on-surface-variant mb-1">Total Sent</p>
            <p className="text-[20px] font-bold text-on-surface">{formatAmount(stats.totalSent)}</p>
          </div>
          <div className="bg-white rounded-2xl border border-surface-variant p-4">
            <p className="text-[11px] font-semibold uppercase text-on-surface-variant mb-1">Total Received</p>
            <p className="text-[20px] font-bold text-secondary">{formatAmount(stats.totalReceived)}</p>
          </div>
          <div className="bg-white rounded-2xl border border-surface-variant p-4">
            <p className="text-[11px] font-semibold uppercase text-on-surface-variant mb-1">Net Flow</p>
            <p className={`text-[20px] font-bold ${stats.netFlow >= 0 ? 'text-secondary' : 'text-error'}`}>
              {stats.netFlow >= 0 ? '+' : ''}{formatAmount(stats.netFlow)}
            </p>
          </div>
          <div className="bg-white rounded-2xl border border-surface-variant p-4">
            <p className="text-[11px] font-semibold uppercase text-on-surface-variant mb-1">Total Txns</p>
            <p className="text-[20px] font-bold text-primary">{stats.txCount}</p>
          </div>
        </div>

        {/* Financial Alert */}
        {stats.ytdIncome > 10000 && (
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 flex gap-3">
            <AlertCircle size={18} className="text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-sm text-amber-800">Tax Planning Reminder</p>
              <p className="text-[12px] text-amber-700 mt-1">
                Your YTD income exceeds $10,000. Consider setting aside funds for tax obligations.
              </p>
            </div>
          </div>
        )}

        {/* Proof of Income */}
        <div className="bg-white rounded-2xl border border-surface-variant p-5">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-xl bg-primary-container flex items-center justify-center">
              <FileText size={20} className="text-white" />
            </div>
            <div>
              <p className="font-semibold text-sm text-on-surface">Proof of Income</p>
              <p className="text-[12px] text-on-surface-variant">
                Generate a printable payslip for visa or loan applications
              </p>
            </div>
          </div>
          <button
            onClick={handleGenerateProof}
            className="w-full bg-primary-container text-white py-3 rounded-xl font-bold text-sm press-effect"
          >
            Generate &amp; Print PDF
          </button>
        </div>

        {/* Financial Tips */}
        <div className="bg-surface-container-low rounded-2xl p-5 space-y-3">
          <p className="text-[12px] font-bold uppercase tracking-wide text-on-surface-variant">
            Financial Tips
          </p>
          {[
            { tip: 'Save 20% of every income for emergencies.', icon: '\u{1F4A1}' },
            { tip: 'Use Split-Routing to automate your savings.', icon: '\u26A1' },
            { tip: 'Keep 3 months of expenses as liquid buffer.', icon: '\u{1F6E1}\uFE0F' },
          ].map(({ tip, icon }) => (
            <div key={tip} className="flex items-start gap-3">
              <span className="text-base flex-shrink-0">{icon}</span>
              <p className="text-sm text-on-surface leading-snug">{tip}</p>
            </div>
          ))}
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
